const express = require("express");
const cors = require("cors");
const app = express();
const port = process.env.PORT || 3001;

app.use(cors());

const data = [
  {
    identifiant: "M0002",
    nom_officiel: "musée de La Poterie",
    adresse: "2 rue de Kuhlendorf",
    code_postal: "67660",
    ville: "Betschdorf",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.betschdorf.com/vie-culturelle-et-associative/musee-de-la-poterie",
    picture: null,
    coordonnees: {
      lon: 7.914409,
      lat: 48.900348,
    },
  },
  {
    identifiant: "M0018",
    nom_officiel: "musée des Arts Décoratifs",
    adresse: "2 place du château",
    lieu: "palais Rohan",
    code_postal: "67000",
    ville: "Strasbourg",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.musees.strasbourg.eu/musee-des-arts-decoratifs",
    picture: null,
    coordonnees: {
      lon: 7.751984,
      lat: 48.581229,
    },
  },
  {
    identifiant: "M0019",
    nom_officiel: "musée des Beaux-Arts",
    adresse: "2 place du château",
    lieu: "palais Rohan",
    code_postal: "67000",
    ville: "Strasbourg",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.musees.strasbourg.eu/musee-des-beaux-arts",
    picture: null,
    coordonnees: {
      lon: 7.751984,
      lat: 48.581229,
    },
  },
  {
    identifiant: "M0025",
    nom_officiel: "musée gallo-romain",
    adresse: "place de la mairie",
    lieu: "le Capitole",
    code_postal: "68600",
    ville: "Biesheim",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "www.biesheim.fr/culture-loisirs/musee-gallo-romain/",
    telephone: "03 89 72 01 58",
    picture: null,
    coordonnees: {
      lon: 7.54802,
      lat: 48.041667,
    },
  },
  {
    identifiant: "M0011",
    nom_officiel: "musée historique et industriel - musée du fer",
    adresse: "9 rue Jeanne d'Arc",
    lieu: null,
    code_postal: "67110",
    ville: "Reichshoffen",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.reichshoffen.fr/Le-Musee-Historique-et-Industriel.html",
    picture: null,
    coordonnees: {
      lon: 7.664814,
      lat: 48.932234,
    },
  },
  {
    identifiant: "M0016",
    nom_officiel: "musée d'art moderne et contemporain de Strasbourg",
    adresse: "1 place Hans Jean Arp",
    lieu: null,
    code_postal: "67000",
    ville: "Strasbourg",
    region: "Grand Est",
    departement: "Bas-Rhin",
    picture: null,
    coordonnees: {
      lon: 7.736231,
      lat: 48.579654,
    },
  },
  {
    identifiant: "M0024",
    nom_officiel: "musée Sundgauvien",
    adresse: "1 rue de l'hôtel de ville",
    lieu: null,
    code_postal: "68130",
    ville: "Altkirch",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "altkirch-alsace.fr/musee-sundgauvien/",
    picture: null,
    coordonnees: {
      lon: 7.237204,
      lat: 47.623329,
    },
  },
  {
    identifiant: "M0026",
    nom_officiel: "musée de la Porte de Thann",
    adresse: "rue de Thann",
    lieu: null,
    code_postal: "68700",
    ville: "Cernay",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "www.musee-cernay.org/",
    picture: null,
    coordonnees: {
      lon: 7.174264,
      lat: 47.809586,
    },
  },
  {
    identifiant: "M0032",
    nom_officiel: "musée du vignoble et des vins d'Alsace",
    adresse: "9 rue de l'ours",
    lieu: "château de la confrérie Saint-Étienne",
    code_postal: "68770",
    ville: "Kientzheim",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "www.musee-du-vignoble-alsace.fr/",
    picture: null,
    coordonnees: {
      lon: 7.280128,
      lat: 48.126069,
    },
  },
  {
    identifiant: "M0040",
    nom_officiel: "musée Vauban",
    adresse: "porte de Belfort",
    lieu: null,
    code_postal: "68600",
    ville: "Neuf-Brisach",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "www.neuf-brisach.fr/Culture-Patrimoine/Musee.html",
    picture: null,
    coordonnees: {
      lon: 7.525674,
      lat: 48.016144,
    },
  },
  {
    identifiant: "M0047",
    nom_officiel: "musée de la société d’histoire “ les amis de Thann ”",
    adresse: "24 rue Saint-Thiébaut",
    lieu: null,
    code_postal: "68800",
    ville: "Thann",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "www.les-amis-de-thann.com/",
    picture: null,
    coordonnees: {
      lon: 7.101737,
      lat: 47.812283,
    },
  },
  {
    identifiant: "M0296",
    nom_officiel: "musée du Château-Fort",
    adresse: "château fort",
    lieu: null,
    code_postal: "08200",
    ville: "Sedan",
    region: "Grand Est",
    departement: "Ardennes",
    url: "musee-municipal-sedan.over-blog.com/a-propos-du-musee.html",
    picture:
      "https://www.chateau-fort-sedan.fr/wp-content/uploads/2022/03/galerie-accueil-4.jpg",
    coordonnees: {
      lon: 4.919074,
      lat: 49.695347,
    },
  },
  {
    identifiant: "M0319",
    nom_officiel: "musée des Beaux-Arts et d'Archéologie",
    adresse: "place du palais",
    lieu: null,
    code_postal: "52000",
    ville: "Chaumont",
    region: "Grand Est",
    departement: "Haute-Marne",
    url: "www.tourisme-chaumont-champagne.com/patrimoine-culturel/musee-d-art-et-d-histoire-de-chaumont,fr,16,pcu15",
    coordonnees: {
      lon: 5.137331,
      lat: 48.112482,
    },
  },
  {
    identifiant: "M0322",
    nom_officiel: "musée de la Coutellerie",
    adresse: "place Charles de Gaulle",
    lieu: null,
    code_postal: "52800",
    ville: "Nogent",
    region: "Grand Est",
    departement: "Haute-Marne",
    url: "www.villedenogent52.fr/page/culture/musee/",
    coordonnees: {
      lon: 5.341424,
      lat: 48.02758,
    },
  },
  {
    identifiant: "M0290",
    nom_officiel: "Musée de la Maison de la Dernière Cartouche",
    adresse: "12 avenue de la dernière cartouche",
    lieu: null,
    code_postal: "08140",
    ville: "Bazeilles",
    region: "Grand Est",
    departement: "Ardennes",
    url: "www.maisondeladernierecartouche.com/index.php?lang=fr",
    picture:
      "https://cdn.iris-etourism.io/uploads/adt_ardennes/42b/fd02f576-7157-44df-b9a4-6c8c6173aaca-g91.webp",
    coordonnees: {
      lon: 4.975035,
      lat: 49.681745,
    },
  },
  {
    identifiant: "M0299",
    nom_officiel: "musée Napoléon Ier",
    adresse: "34 rue de l'école militaire",
    lieu: null,
    code_postal: "10500",
    ville: "Brienne-le-Château",
    region: "Grand Est",
    departement: "Aube",
    url: "www.musee-napoleon-brienne.fr/lhistoire-du-musee",
    coordonnees: {
      lon: 4.528446,
      lat: 48.388915,
    },
  },
  {
    identifiant: "M0302",
    nom_officiel: "musée d'Art Moderne",
    adresse: "14 place Saint-Pierre",
    lieu: "ancien évêché",
    code_postal: "10000",
    ville: "Troyes",
    region: "Grand Est",
    departement: "Aube",
    url: "www.musees-troyes.com/art-moderne/",
    coordonnees: {
      lon: 4.080736,
      lat: 48.299643,
    },
  },
  {
    identifiant: "M0321",
    nom_officiel: "musée d'art et d'histoire",
    adresse: "place du centenaire",
    lieu: null,
    code_postal: "52200",
    ville: "Langres",
    region: "Grand Est",
    departement: "Haute-Marne",
    url: "www.musees-langres.fr/",
    coordonnees: {
      lon: 5.333286,
      lat: 47.865268,
    },
  },
  {
    identifiant: "M0513",
    nom_officiel: "musée de l'Ecole de Nancy",
    adresse: "36-38 rue du Sergent Blandan",
    lieu: null,
    code_postal: "54000",
    ville: "Nancy",
    region: "Grand Est",
    departement: "Meurthe-et-Moselle",
    url: "www.ecole-de-nancy.com/web/",
    coordonnees: {
      lon: 6.166351,
      lat: 48.680494,
    },
  },
  {
    identifiant: "M0522",
    nom_officiel: "musée de la bière et du pays de Stenay",
    adresse: "17 rue du moulin",
    lieu: null,
    code_postal: "55700",
    ville: "Stenay",
    region: "Grand Est",
    departement: "Meuse",
    url: "museedelabiere.com/",
    picture:
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/96/31/50/aussenansicht.jpg?w=1200&h=-1&s=1",
    coordonnees: {
      lon: 5.186786,
      lat: 49.48769,
    },
  },
  {
    identifiant: "M0536",
    nom_officiel: "musée départemental d'art ancien et contemporain",
    adresse: "1 place de Lagarde",
    lieu: null,
    code_postal: "88000",
    ville: "Epinal",
    region: "Grand Est",
    departement: "Vosges",
    url: "mudaac.vosges.fr/",
    coordonnees: {
      lon: 6.446595,
      lat: 48.17326,
    },
  },
  {
    identifiant: "M0510",
    nom_officiel: "musée municipal des émaux et faïences",
    adresse: "porte de France",
    lieu: null,
    code_postal: "54400",
    ville: "Longwy",
    region: "Grand Est",
    departement: "Meurthe-et-Moselle",
    url: "museedesemaux.wordpress.com/",
    coordonnees: {
      lon: 5.760104,
      lat: 49.519776,
    },
  },
  {
    identifiant: "M0531",
    nom_officiel: "musée militaire et Erckmann-Chatrian",
    adresse: "place d'armes",
    lieu: "hôtel de ville",
    code_postal: "57370",
    ville: "Phalsbourg",
    region: "Grand Est",
    departement: "Moselle",
    url: "www.phalsbourg.fr/La_culture__les_loisirs/Le_musee",
    coordonnees: {
      lon: 7.259055,
      lat: 48.766548,
    },
  },
  {
    identifiant: "M1162",
    nom_officiel: "musée Lalique",
    adresse: "40 rue du Hochberg",
    lieu: null,
    code_postal: "67290",
    ville: "Wingen-sur-Moder",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.musee-lalique.com",
    coordonnees: {
      lon: 7.361922,
      lat: 48.927033,
    },
  },
  {
    identifiant: "M7047",
    nom_officiel: "musée minéralogique de la Société industrielle de Mulhouse",
    adresse: "3 avenue Alfred Werner",
    lieu: "école de chimie",
    code_postal: "68100",
    ville: "Mulhouse",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "www.enscmu.uha.fr/index.php/lenscmu/histoire-et-patrimoine/",
    coordonnees: {
      lon: 7.310303,
      lat: 47.73132,
    },
  },
  {
    identifiant: "M7048",
    nom_officiel: "muséum-Aquarium de Nancy",
    adresse: "34 rue Sainte-Catherine",
    lieu: null,
    code_postal: "54000",
    ville: "Nancy",
    region: "Grand Est",
    departement: "Meurthe-et-Moselle",
    url: "www.museumaquariumdenancy.eu/accueil/",
    coordonnees: {
      lon: 6.188467,
      lat: 48.695072,
    },
  },
  {
    identifiant: "M1216",
    nom_officiel: "musée de la bonneterie",
    adresse: "4 rue de Vauluisant",
    lieu: "hôtel de Vauluisant",
    code_postal: "10000",
    ville: "Troyes",
    region: "Grand Est",
    departement: "Aube",
    url: "www.musees-troyes.com/bonneterie/",
    coordonnees: {
      lon: 4.07187249901482,
      lat: 48.2945564022452,
    },
  },
  {
    identifiant: "M0008",
    nom_officiel: "maison de l'archéologie des Vosges du Nord",
    adresse: "44 avenue Foch",
    lieu: null,
    code_postal: "67110",
    ville: "Niederbronn-Les-Bains",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.niederbronn-les-bains.fr/culture-et-loisirs/maison-de-l-archeologie.html",
    coordonnees: {
      lon: 7.650428,
      lat: 48.947444,
    },
  },
  {
    identifiant: "M0036",
    nom_officiel: "musée Français du Chemin de Fer",
    adresse: "2 rue Alfred de Glehn",
    lieu: null,
    code_postal: "68200",
    ville: "Mulhouse",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "www.citedutrain.com/",
    coordonnees: {
      lon: 7.312824,
      lat: 47.732372,
    },
  },
  {
    identifiant: "M0038",
    nom_officiel: "musée du Sapeur-Pompier",
    adresse: "12-14 rue de Luppach",
    lieu: null,
    code_postal: "68480",
    ville: "Vieux-Ferrette",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "www.musee-sapeur-pompier.fr/",
    coordonnees: {
      lon: 7.304287,
      lat: 47.504301,
    },
  },
  {
    identifiant: "M0041",
    nom_officiel: "musée Paysan",
    adresse: "10 rue principale",
    lieu: null,
    code_postal: "68480",
    ville: "Oltingue",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "musee.paysan.free.fr/",
    coordonnees: {
      lon: 7.391275,
      lat: 47.492827,
    },
  },
  {
    identifiant: "M0001",
    nom_officiel: "musée de la Folie Marco",
    adresse: "30 rue du docteur Sultzer",
    lieu: null,
    code_postal: "67140",
    ville: "Barr",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.musee-foliemarco.com",
    coordonnees: {
      lon: 7.451102,
      lat: 48.410166,
    },
  },
  {
    identifiant: "M0012",
    nom_officiel: "musée du Château des Rohan",
    adresse: "place du général de Gaulle",
    lieu: "château des Rohan",
    code_postal: "67700",
    ville: "Saverne",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.saverne.fr/sport-culture/offre-culturelle/musee-de-saverne/",
    coordonnees: {
      lon: 7.362787,
      lat: 48.741958,
    },
  },
  {
    identifiant: "M0031",
    nom_officiel: "musée historique",
    adresse: "64 rue du général de Gaulle",
    lieu: null,
    code_postal: "68240",
    ville: "Kaysersberg",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "www.kaysersberg-vignoble.fr/musee-historique",
    coordonnees: {
      lon: 7.261441,
      lat: 48.139072,
    },
  },
  {
    identifiant: "M0033",
    nom_officiel: "musée des Beaux-Arts",
    adresse: "4 place Guillaume Tell",
    lieu: "maison Steinbach",
    code_postal: "68100",
    ville: "Mulhouse",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "musees-mulhouse.fr/musees/musee-des-beaux-arts/",
    coordonnees: {
      lon: 7.338271,
      lat: 47.745774,
    },
  },
  {
    identifiant: "M0291",
    nom_officiel: "musée Arthur Rimbaud",
    adresse: "quai Arthur Rimbaud",
    lieu: "vieux-moulin",
    code_postal: "08000",
    ville: "Charleville-Mézières",
    region: "Grand Est",
    departement: "Ardennes",
    url: "www.charleville-mezieres.fr/musee-rimbaud",
    picture:
      "https://upload.wikimedia.org/wikipedia/commons/6/6e/Musee-Rimbaud-fa%C3%A7ade.jpg",
    coordonnees: {
      lon: 4.720613,
      lat: 49.776034,
    },
  },
  {
    identifiant: "M0297",
    nom_officiel: "musée municipal",
    adresse: "mairie",
    lieu: "place Carnot",
    code_postal: "10200",
    ville: "Bar-sur-Aube",
    region: "Grand Est",
    departement: "Aube",
    url: "https://www.aube-champagne.com/fr/les-musees/",
    coordonnees: {
      lon: 4.705996,
      lat: 48.233206,
    },
  },
  {
    identifiant: "M0301",
    nom_officiel: "musée Camille Claudel",
    adresse: "10 rue Gustave Flaubert",
    lieu: null,
    code_postal: "10400",
    ville: "Nogent-sur-Seine",
    region: "Grand Est",
    departement: "Aube",
    url: "www.museecamilleclaudel.fr/fr",
    picture:
      "https://upload.wikimedia.org/wikipedia/commons/9/94/Le_Mus%C3%A9e_Camille_Claudel_%28Nogent-sur-Seine%29_%2843980921631%29.jpg",
    coordonnees: {
      lon: 3.500892,
      lat: 48.494242,
    },
  },
  {
    identifiant: "M0306",
    nom_officiel: "maison de l'outil et de la pensée ouvrière",
    adresse: "7 rue de la Trinité",
    lieu: "hôtel de Mauroy",
    code_postal: "10000",
    ville: "Troyes",
    region: "Grand Est",
    departement: "Aube",
    url: "mopo3.com/",
    coordonnees: {
      lon: 4.072849,
      lat: 48.29473,
    },
  },
  {
    identifiant: "M0320",
    nom_officiel: "Maison des Lumières Denis Diderot",
    adresse: "1 place Pierre Burelle",
    lieu: null,
    code_postal: "52200",
    ville: "Langres",
    region: "Grand Est",
    departement: "Haute-Marne",
    url: "www.musees-langres.fr/maison-des-lumieres-denis-diderot/",
    coordonnees: {
      lon: 5.331753,
      lat: 47.866417,
    },
  },
  {
    identifiant: "M0303",
    nom_officiel: "musée des beaux-arts et d’archéologie",
    adresse: "rue Chrestien de Troyes",
    lieu: "abbaye Saint-Loup",
    code_postal: "10000",
    ville: "Troyes",
    region: "Grand Est",
    departement: "Aube",
    url: "www.musees-troyes.com",
    coordonnees: {
      lon: 4.08003,
      lat: 48.300638,
    },
  },
  {
    identifiant: "M0309",
    nom_officiel: "musée municipal",
    adresse: "13 avenue de Champagne",
    lieu: "château Perrier",
    code_postal: "51200",
    ville: "Epernay",
    region: "Grand Est",
    departement: "Marne",
    url: "archeochampagne.epernay.fr/",
    picture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Ch%C3%A2teau-Perrier.JPG/1920px-Ch%C3%A2teau-Perrier.JPG",
    coordonnees: {
      lon: 3.961379,
      lat: 49.042901,
    },
  },
  {
    identifiant: "M0315",
    nom_officiel: "musée de l'Argonne Viard-Morel",
    adresse: "place Leclerc",
    lieu: null,
    code_postal: "51800",
    ville: "Sainte-Menehould",
    region: "Grand Est",
    departement: "Marne",
    url: "www.mmc-stemenehould.com/musee-d-art-et-d-histoire/",
    picture:
      "https://cdt51.media.tourinsoft.eu/upload/Office-du-Tourisme-de-l-Argonne-Champenoise-.jpeg",
    coordonnees: {
      lon: 4.897997,
      lat: 49.092086,
    },
  },
  {
    identifiant: "M0323",
    nom_officiel: "musée Municipal",
    adresse: "17 rue de la victoire",
    lieu: null,
    code_postal: "52115",
    ville: "Saint-Dizier",
    region: "Grand Est",
    departement: "Haute-Marne",
    url: "www.saint-dizier.fr/sport-culture-loisirs/culture-et-musique/musee-de-saint-dizier.html",
    picture:
      "https://www.saint-dizier.fr/fileadmin/user_upload/mediatheque/ville_agglo/pages/sport_culture_loisirs/musee/musee-saint-dizier-square-winston-churchill-c-erick-colin.jpg",
    coordonnees: {
      lon: 4.94827773339682,
      lat: 48.638041229332,
    },
  },
  {
    identifiant: "M0527",
    nom_officiel: "musée du Sel",
    adresse: "porte de France",
    lieu: null,
    code_postal: "57630",
    ville: "Marsal",
    region: "Grand Est",
    departement: "Moselle",
    url: "www.mosellepassion.fr/index.php/les-sites-moselle-passion/musee-du-sel",
    coordonnees: {
      lon: 6.606549,
      lat: 48.788503,
    },
  },
  {
    identifiant: "M0507",
    nom_officiel: "musée Les Sources d'Hercule",
    adresse: "1 place Jean-Marie Keyser",
    lieu: null,
    code_postal: "54120",
    ville: "Deneuvre",
    region: "Grand Est",
    departement: "Meurthe-et-Moselle",
    url: "www.museehercule.com/",
    coordonnees: {
      lon: 6.734719,
      lat: 48.446385,
    },
  },
  {
    identifiant: "M0518",
    nom_officiel: "musée de la céramique et de l'ivoire",
    adresse: "7 avenue Carcano",
    lieu: null,
    code_postal: "55200",
    ville: "Commercy",
    region: "Grand Est",
    departement: "Meuse",
    url: "musees-meuse.fr/musee-de-la-ceramique-et-de-livoire-commercy/",
    coordonnees: {
      lon: 5.58962,
      lat: 48.76331,
    },
  },
  {
    identifiant: "M0528",
    nom_officiel: "Maison du Verre et du Cristal",
    adresse: "place Robert Schuman",
    lieu: null,
    code_postal: "57960",
    ville: "Meisenthal",
    region: "Grand Est",
    departement: "Moselle",
    url: "ciav-meisenthal.fr/rubrique/apropos",
    coordonnees: {
      lon: 7.352438,
      lat: 48.964935,
    },
  },
  {
    identifiant: "M0537",
    nom_officiel: "musée de l'image",
    adresse: "42 quai Dogneville",
    lieu: null,
    code_postal: "88000",
    ville: "Epinal",
    region: "Grand Est",
    departement: "Vosges",
    url: "museedelimage.fr/",
    coordonnees: {
      lon: 6.445992,
      lat: 48.183628,
    },
  },
  {
    identifiant: "M0539",
    nom_officiel: "musée Louis Français",
    adresse: "30 avenue Louis Français",
    lieu: null,
    code_postal: "88370",
    ville: "Plombières-Les-Bains",
    region: "Grand Est",
    departement: "Vosges",
    url: "www.plombieres-les-bains.fr/fr/musee-du-paysage-louis-francais.html",
    coordonnees: {
      lon: 6.458494,
      lat: 47.964095,
    },
  },
  {
    identifiant: "M7071",
    nom_officiel:
      "musée zoologique de l'université Louis Pasteur et de la ville de Strasbourg",
    adresse: "29 boulevard de la Victoire",
    lieu: null,
    code_postal: "67000",
    ville: "Strasbourg",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.musees.strasbourg.eu/musee-zoologique",
    coordonnees: {
      lon: 7.764645,
      lat: 48.582707,
    },
  },
  {
    identifiant: "M1098",
    nom_officiel: "musée Tomi Ungerer",
    adresse: "2 avenue de la Marseillaise",
    lieu: "villa Greiner",
    code_postal: "67000",
    ville: "Strasbourg",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.musees.strasbourg.eu/musee-tomi-ungerer",
    coordonnees: {
      lon: 7.755028,
      lat: 48.585747,
    },
  },
  {
    identifiant: "M0004",
    nom_officiel: "musée alsacien",
    adresse: "1 place Joseph Thierry",
    lieu: null,
    code_postal: "67500",
    ville: "Haguenau",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.ville-haguenau.fr/musee-alsacien",
    coordonnees: {
      lon: 7.789527,
      lat: 48.814611,
    },
  },
  {
    identifiant: "M0006",
    nom_officiel: "musée de la chartreuse",
    adresse: "4 cour des Chartreux",
    lieu: null,
    code_postal: "67120",
    ville: "Molsheim",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.chartreuse-molsheim.info",
    coordonnees: {
      lon: 7.49023,
      lat: 48.54278,
    },
  },
  {
    identifiant: "M0014",
    nom_officiel: "musée Alsacien",
    adresse: "23 quai Saint-Nicolas",
    lieu: null,
    code_postal: "67000",
    ville: "Strasbourg",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.musees.strasbourg.eu/musee-alsacien",
    coordonnees: {
      lon: 7.750484,
      lat: 48.579075,
    },
  },
  {
    identifiant: "M0017",
    nom_officiel: "musée de l'Œuvre Notre-Dame",
    adresse: "3 place du château",
    lieu: null,
    code_postal: "67076",
    ville: "Strasbourg",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.musees.strasbourg.eu/musee-de-l-oeuvre-notre-dame",
    coordonnees: {
      lon: 7.75139111349292,
      lat: 48.5809830491392,
    },
  },
  {
    identifiant: "M0030",
    nom_officiel: "musée Historique et Militaire",
    adresse: "6 rue des boulangers",
    lieu: null,
    code_postal: "68330",
    ville: "Huningue",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "www.ville-huningue.fr/fr/musee-historique-et-militaire/",
    coordonnees: {
      lon: 7.584985,
      lat: 47.591513,
    },
  },
  {
    identifiant: "M0039",
    nom_officiel: "musée Electropolis",
    adresse: "55 rue du pâturage",
    lieu: null,
    code_postal: "68200",
    ville: "Mulhouse",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "www.musee-electropolis.fr/",
    coordonnees: {
      lon: 7.295058,
      lat: 47.749441,
    },
  },
  {
    identifiant: "M0005",
    nom_officiel: "musée historique",
    adresse: "9 rue du maréchal Foch",
    lieu: null,
    code_postal: "67500",
    ville: "Haguenau",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.ville-haguenau.fr/musee-historique",
    coordonnees: {
      lon: 7.791481,
      lat: 48.812831,
    },
  },
  {
    identifiant: "M0010",
    nom_officiel: "musée de l'Image Populaire",
    adresse: "24 rue du docteur Albert Schweitzer",
    lieu: null,
    code_postal: "67350",
    ville: "Val-de-Moder",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.commune-valdemoder.fr/culture-loisirs/musee-de-l-image-populaire",
    coordonnees: {
      lon: 7.611365,
      lat: 48.844834,
    },
  },
  {
    identifiant: "M0013",
    nom_officiel: "cabinet des estampes et des dessins",
    adresse: "5 place du château",
    lieu: null,
    code_postal: "67076",
    ville: "Strasbourg",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.musees.strasbourg.eu/cabinet-des-estampes-et-des-dessins",
    coordonnees: {
      lon: 7.75054432713545,
      lat: 48.5812366410149,
    },
  },
  {
    identifiant: "M0044",
    nom_officiel: "musée du papier peint",
    adresse: "28 rue Zuber",
    lieu: "la commanderie",
    code_postal: "68170",
    ville: "Rixheim",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "www.museepapierpeint.org/fr/",
    coordonnees: {
      lon: 7.397424,
      lat: 47.744135,
    },
  },
  {
    identifiant: "M0293",
    nom_officiel: "musée",
    adresse: "mairie",
    lieu: null,
    code_postal: "08600",
    ville: "Givet",
    region: "Grand Est",
    departement: "Ardennes",
    url: "https://www.charleville-mezieres.fr/le-musee-de-lardenne",
    coordonnees: {
      lon: 4.82452731306089,
      lat: 50.1365822914299,
    },
  },
  {
    identifiant: "M0307",
    nom_officiel: "musée municipal",
    adresse: "place Godart",
    lieu: null,
    code_postal: "51000",
    ville: "Châlons-en-Champagne",
    region: "Grand Est",
    departement: "Marne",
    url: "www.chalonsenchampagne.fr/culture/musees",
    picture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Mus%C3%A9e_Chaalons_3545.JPG/1920px-Mus%C3%A9e_Chaalons_3545.JPG",
    coordonnees: {
      lon: 4.364203,
      lat: 48.956391,
    },
  },
  {
    identifiant: "M0312",
    nom_officiel: "musée Saint-Remi",
    adresse: "53 rue Simon",
    lieu: "ancienne abbaye",
    code_postal: "51100",
    ville: "Reims",
    region: "Grand Est",
    departement: "Marne",
    url: "musees-reims.fr/fr/musees/musee-saint-remi/",
    picture:
      "https://upload.wikimedia.org/wikipedia/commons/4/4c/Reims-Mus%C3%A9e_St_R%C3%A9mi-02.jpg",
    coordonnees: {
      lon: 4.040351,
      lat: 49.243111,
    },
  },
  {
    identifiant: "M0317",
    nom_officiel: "musée municipal",
    adresse: "parc du château",
    lieu: null,
    code_postal: "52400",
    ville: "Bourbonne-Les-Bains",
    region: "Grand Est",
    departement: "Haute-Marne",
    url: "bourbonne.com/detente/culture/",
    coordonnees: {
      lon: 5.732204,
      lat: 47.942274,
    },
  },
  {
    identifiant: "M0294",
    nom_officiel: "Musée du Feutre",
    adresse: "mairie",
    lieu: "place du colombier",
    code_postal: "08210",
    ville: "Mouzon",
    region: "Grand Est",
    departement: "Ardennes",
    url: "www.mouzon.fr/presentation-du-musee.html",
    picture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Mus%C3%A9e_du_feutre.JPG/1920px-Mus%C3%A9e_du_feutre.JPG",
    coordonnees: {
      lon: 5.074601,
      lat: 49.605919,
    },
  },
  {
    identifiant: "M0313",
    nom_officiel: "musée de l’Ancien Collège des Jésuites",
    adresse: "1 place Museux",
    lieu: null,
    code_postal: "51100",
    ville: "Reims",
    region: "Grand Est",
    departement: "Marne",
    url: "https://www.reims-tourisme.com/activite/ancien-college-des-jesuites/",
    picture:
      "https://upload.wikimedia.org/wikipedia/commons/4/4b/Reims_-_ancien_coll%C3%A8ge_des_J%C3%A9suites.JPG",
    coordonnees: {
      lon: 4.040071,
      lat: 49.246527,
    },
  },
  {
    identifiant: "M0509",
    nom_officiel: "Féru des sciences",
    adresse: "1 avenue du général de Gaulle",
    lieu: null,
    code_postal: "54140",
    ville: "Jarville-la-Malgrange",
    region: "Grand Est",
    departement: "Meurthe-et-Moselle",
    url: "www.museehistoiredufer.fr/accueil/",
    coordonnees: {
      lon: 6.208769,
      lat: 48.666588,
    },
  },
  {
    identifiant: "M0515",
    nom_officiel: "musée d’art et d’histoire",
    adresse: "25 rue Gouvion Saint-Cyr",
    lieu: null,
    code_postal: "54200",
    ville: "Toul",
    region: "Grand Est",
    departement: "Meurthe-et-Moselle",
    url: "www.toul.fr/?actuellement-au-musee",
    coordonnees: {
      lon: 5.89134,
      lat: 48.678544,
    },
  },
  {
    identifiant: "M0512",
    nom_officiel: "musée des Beaux-Arts",
    adresse: "3 place Stanislas",
    lieu: null,
    code_postal: "54000",
    ville: "Nancy",
    region: "Grand Est",
    departement: "Meurthe-et-Moselle",
    url: "musee-des-beaux-arts.nancy.fr/accueil-145.html",
    coordonnees: {
      lon: 6.182435,
      lat: 48.693507,
    },
  },
  {
    identifiant: "M0523",
    nom_officiel: "musée d'Argonne",
    adresse: "9 rue Louis XVI",
    lieu: null,
    code_postal: "55270",
    ville: "Varennes-en-Argonne",
    region: "Grand Est",
    departement: "Meuse",
    url: "musees-meuse.fr/musee-dargonne-varennes-en-argonne/",
    picture:
      "https://tourisme-argonne-meuse.fr/wp-content/uploads/elementor/thumbs/musee-VARENNES-27_Michel-PETIT_web-1-p6041bztjuz510vr6niwzkz5g2gze3xjq0s3yijcf4.jpg",
    coordonnees: {
      lon: 5.033072,
      lat: 49.226057,
    },
  },
  {
    identifiant: "M0530",
    nom_officiel: "musée des mines de fer de Lorraine",
    adresse: "2 rue du musée",
    lieu: "mine de Neufchef-Hayange",
    code_postal: "57700",
    ville: "Neufchef",
    region: "Grand Est",
    departement: "Moselle",
    url: "www.musee-minesdefer-lorraine.com",
    coordonnees: {
      lon: 6.027572,
      lat: 49.325904,
    },
  },
  {
    identifiant: "M1085",
    nom_officiel: "musée départemental Georges de La Tour",
    adresse: "place Jeanne d'Arc",
    lieu: null,
    code_postal: "57630",
    ville: "Vic-sur-Seille",
    region: "Grand Est",
    departement: "Moselle",
    url: "www.mosellepassion.fr/index.php/les-sites-moselle-passion/musee-georges-de-la-tour",
    coordonnees: {
      lon: 6.531429,
      lat: 48.781787,
    },
  },
  {
    identifiant: "M1089",
    nom_officiel: "musée de la mine - carreau Wendel",
    adresse: "parc Explor Wendel",
    lieu: "musée les mineurs Wendel",
    code_postal: "57540",
    ville: "Petite-Rosselle",
    region: "Grand Est",
    departement: "Moselle",
    url: "parc-explor.com/",
    coordonnees: {
      lon: 6.848979,
      lat: 49.20684,
    },
  },
  {
    identifiant: "M0542",
    nom_officiel: "musée Pierre Noël - musée de la vie dans les Hautes-Vosges",
    adresse: "place Georges Trimouille",
    lieu: null,
    code_postal: "88100",
    ville: "Saint-Dié-des-Vosges",
    region: "Grand Est",
    departement: "Vosges",
    url: "www.ca-saintdie.fr/decouvrir/musee-pierre-noel/actualites",
    coordonnees: {
      lon: 6.95045993949365,
      lat: 48.2887422846273,
    },
  },
  {
    identifiant: "M0015",
    nom_officiel: "musée archéologique",
    adresse: "2 place du château",
    lieu: "palais Rohan Strasbourg Cedex",
    code_postal: "67000",
    ville: "Strasbourg",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.musees.strasbourg.eu/musee-archeologique",
    coordonnees: {
      lon: 7.751984,
      lat: 48.581229,
    },
  },
  {
    identifiant: "M0022",
    nom_officiel: "musée Westercamp",
    adresse: "1-3 rue du musée",
    lieu: null,
    code_postal: "67160",
    ville: "Wissembourg",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "webmuseo.com/ws/musee-wissembourg/app/report/index.html",
    coordonnees: {
      lon: 7.944344,
      lat: 49.038815,
    },
  },
  {
    identifiant: "M0020",
    nom_officiel: "musée historique",
    adresse: "2 rue du vieux marché aux poissons",
    lieu: "musée historique",
    code_postal: "67000",
    ville: "Strasbourg",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.musees.strasbourg.eu/musee-historique",
    coordonnees: {
      lon: 7.749714,
      lat: 48.580579,
    },
  },
  {
    identifiant: "M0035",
    nom_officiel: "musée national de l'automobile - collection Schlumpf",
    adresse: "192 avenue de Colmar",
    lieu: "BP 1096",
    code_postal: "68051",
    ville: "Mulhouse",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "www.citedelautomobile.com/",
    coordonnees: {
      lon: 7.32789352526163,
      lat: 47.7616141670104,
    },
  },
  {
    identifiant: "M0314",
    nom_officiel: "musée-hôtel Le Vergeur",
    adresse: "36 place du forum",
    lieu: "hôtel Le Vergeur",
    code_postal: "51100",
    ville: "Reims",
    region: "Grand Est",
    departement: "Marne",
    url: "musees-reims.fr/fr/musees/musee-le-vergeur/",
    picture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Le_vergeur_007.JPG/1920px-Le_vergeur_007.JPG",
    coordonnees: {
      lon: 4.034043,
      lat: 49.257013,
    },
  },
  {
    identifiant: "M0295",
    nom_officiel: "musée du Rethélois et du Porcien",
    adresse: "Rond-point de l'Octroi",
    lieu: null,
    code_postal: "08300",
    ville: "Rethel",
    region: "Grand Est",
    departement: "Ardennes",
    url: "https://musee-chateau.fr/musee-rethelois-porcien-rethel-08300/",
    picture:
      "https://www.museesgrandest.org/wp-content/uploads/2019/01/rethel-agora.jpg",
    coordonnees: {
      lon: 4.366447,
      lat: 49.509328,
    },
  },
  {
    identifiant: "M0304",
    nom_officiel: "musée historique de Troyes et de la Champagne",
    adresse: "4 rue de Vauluisant",
    lieu: "hôtel de Vauluisant",
    code_postal: "10000",
    ville: "Troyes",
    region: "Grand Est",
    departement: "Aube",
    url: "www.musees-troyes.com/art-champenois/",
    coordonnees: {
      lon: 4.071824,
      lat: 48.294239,
    },
  },
  {
    identifiant: "M0308",
    nom_officiel: "musée Garinet",
    adresse: "13 rue Pasteur",
    lieu: null,
    code_postal: "51000",
    ville: "Châlons-en-Champagne",
    region: "Grand Est",
    departement: "Marne",
    url: "www.chalonsenchampagne.fr/culture-et-tourisme/a-votre-service/musees-municipaux",
    picture:
      "https://upload.wikimedia.org/wikipedia/commons/2/27/Cot%C3%A9_jardin_mus%C3%A9e_Garinet.jpg",
    coordonnees: {
      lon: 4.366501,
      lat: 48.955859,
    },
  },
  {
    identifiant: "M0311",
    nom_officiel: "musée des Beaux-Arts de Reims",
    adresse: "8 rue Chanzy",
    lieu: "ancienne abbaye de Saint-Denis",
    code_postal: "51100",
    ville: "Reims",
    region: "Grand Est",
    departement: "Marne",
    url: "musees-reims.fr/fr/musees/musee-des-beaux-arts/",
    picture:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Mus%C3%A9e_des_beaux_arts_024.JPG/1920px-Mus%C3%A9e_des_beaux_arts_024.JPG",
    coordonnees: {
      lon: 4.030921,
      lat: 49.253442,
    },
  },
  {
    identifiant: "M0318",
    nom_officiel: "musée de l'Affiche",
    adresse: "1 place Émile Goguenheim",
    lieu: "ancienne Banque de France",
    code_postal: "52000",
    ville: "Chaumont",
    region: "Grand Est",
    departement: "Haute-Marne",
    url: "www.centrenationaldugraphisme.fr/le-signe",
    coordonnees: {
      lon: 5.135234,
      lat: 48.110756,
    },
  },
  {
    identifiant: "M0511",
    nom_officiel: "musée du château",
    adresse: "place de la 2e D.C.",
    lieu: "château",
    code_postal: "54300",
    ville: "Lunéville",
    region: "Grand Est",
    departement: "Meurthe-et-Moselle",
    url: "www.chateauluneville.meurthe-et-moselle.fr/",
    coordonnees: {
      lon: 6.505708,
      lat: 48.589446,
    },
  },
  {
    identifiant: "M0521",
    nom_officiel: "musée départemental Raymond Poincaré",
    adresse: "14 rue du château",
    lieu: "Le Clos",
    code_postal: "55300",
    ville: "Sampigny",
    region: "Grand Est",
    departement: "Meuse",
    url: "musees-meuse.fr/musee-departemental-raymond-poincare-sampigny/",
    coordonnees: {
      lon: 5.50824,
      lat: 48.827583,
    },
  },
  {
    identifiant: "M0533",
    nom_officiel: "musée de la faïence et des techniques faïencières",
    adresse: "15-17 rue Poincaré",
    lieu: null,
    code_postal: "57200",
    ville: "Sarreguemines",
    region: "Grand Est",
    departement: "Moselle",
    url: "www.sarreguemines-museum.fr",
    coordonnees: {
      lon: 7.070473,
      lat: 49.109069,
    },
  },
  {
    identifiant: "M0538",
    nom_officiel: "musée de la lutherie",
    adresse: "cours Stanislas",
    lieu: null,
    code_postal: "88503",
    ville: "Mirecourt",
    region: "Grand Est",
    departement: "Vosges",
    url: "musee-lutherie-mirecourt.fr/",
    coordonnees: {
      lon: 6.13544043996407,
      lat: 48.30159282877,
    },
  },
  {
    identifiant: "M0517",
    nom_officiel: "musée barrois",
    adresse: "esplanade du château",
    lieu: null,
    code_postal: "55000",
    ville: "Bar-le-Duc",
    region: "Grand Est",
    departement: "Meuse",
    url: "musees-meuse.fr/musee-barrois/",
    picture:
      "https://lh3.googleusercontent.com/p/AF1QipPm6SJEgBUcn4s04wOk2x24-KY5ETrBb3cECqKA=s1360-w1360-h10200",
    coordonnees: {
      lon: 5.156074,
      lat: 48.771797,
    },
  },
  {
    identifiant: "M0524",
    nom_officiel: "musée Jeanne d'Arc",
    adresse: "rue Jeanne d'Arc",
    lieu: "hôtel de ville",
    code_postal: "55140",
    ville: "Vaucouleurs",
    region: "Grand Est",
    departement: "Meuse",
    url: "musees-meuse.fr/musee-jeanne-darc-vaucouleurs/",
    coordonnees: {
      lon: 5.666,
      lat: 48.602652,
    },
  },
  {
    identifiant: "M0526",
    nom_officiel: "musée de la guerre de 1870",
    adresse: "11 rue de Metz",
    lieu: null,
    code_postal: "57130",
    ville: "Gravelotte",
    region: "Grand Est",
    departement: "Moselle",
    url: "www.mosellepassion.fr/index.php/les-sites-moselle-passion/musee-de-la-guerre-de-1870",
    coordonnees: {
      lon: 6.029871,
      lat: 49.113679,
    },
  },
  {
    identifiant: "M0541",
    nom_officiel: "musée Charles Friry",
    adresse: "12 rue du général Humbert",
    lieu: null,
    code_postal: "88200",
    ville: "Remiremont",
    region: "Grand Est",
    departement: "Vosges",
    url: "www.remiremont.fr/culture/musees-de-remiremont/musee-charles-friry/",
    coordonnees: {
      lon: 6.590031,
      lat: 48.015174,
    },
  },
  {
    identifiant: "M7073",
    nom_officiel: "muséum d’histoire naturelle",
    adresse: "1 rue Chrestien de Troyes",
    lieu: "abbaye Saint-Loup",
    code_postal: "10000",
    ville: "Troyes",
    region: "Grand Est",
    departement: "Aube",
    url: "www.musees-troyes.com/museum/",
    coordonnees: {
      lon: 4.08003,
      lat: 48.300638,
    },
  },
  {
    identifiant: "M0003",
    nom_officiel: "musée du Pays de Hanau - histoire et vies d’un territoire",
    adresse: "3 place du château",
    lieu: "halle aux blés",
    code_postal: "67330",
    ville: "Bouxwiller",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "www.museedupaysdehanau.eu",
    coordonnees: {
      lon: 7.482915,
      lat: 48.824977,
    },
  },
  {
    identifiant: "M0021",
    nom_officiel: "musée Oberlin",
    adresse: "25 montée Oberlin",
    lieu: null,
    code_postal: "67130",
    ville: "Waldersbach",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "musee-oberlin.org",
    coordonnees: {
      lon: 7.214925,
      lat: 48.414759,
    },
  },
  {
    identifiant: "M0023",
    nom_officiel: "musée de la bataille du 6 août 1870",
    adresse: "2 rue du moulin",
    lieu: "château-mairie",
    code_postal: "67360",
    ville: "Woerth",
    region: "Grand Est",
    departement: "Bas-Rhin",
    url: "webmuseo.com/ws/musee-woerth/app/report/index.html",
    coordonnees: {
      lon: 7.747992,
      lat: 48.938618,
    },
  },
  {
    identifiant: "M0027",
    nom_officiel: "musée Bartholdi",
    adresse: "30 rue des marchands",
    lieu: null,
    code_postal: "68000",
    ville: "Colmar",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "www.musee-bartholdi.fr/",
    coordonnees: {
      lon: 7.357746,
      lat: 48.076747,
    },
  },
  {
    identifiant: "M0028",
    nom_officiel: "musée d'Unterlinden",
    adresse: "place Unterlinden",
    lieu: null,
    code_postal: "68000",
    ville: "Colmar",
    region: "Grand Est",
    departement: "Haut-Rhin",
    url: "www.musee-unterlinden.com/",
    coordonnees: {
      lon: 7.355464,
      lat: 48.079918,
    },
  },
];

app.get("/api/museums", (req, res) => {
  res.json(museums);
});

app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
